baseURL: 'https://alexisconia.com'
languageCode: 'en-us'
title: 'Alexis CONIA'
theme: 'PaperMod'
defaultContentLanguage: en
enableRobotsTXT: true

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 2


params:
  env: production
  title: 'Alexis CONIA'
  description: 'Blog about Microsoft 365, Teams and videoconferencing'
  author: Me
  theme: 'PaperMod'

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: truehugo s

  cover:
    responsiveImages: true

  profileMode:
    enabled: false
    title: "Hi there, \U0001F44B" # optional default will be site title
    subtitle: "I'm software engineer working to build collaboration products based on Microsoft 365 platform and I'm also member of the Microsoft MVP community."
    imageUrl: "/profile.png" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "I'm software engineer working to build collaboration products based on Microsoft 365 platform and I'm also member of the Microsoft MVP community."
  socialIcons:
  - name: twitter
    url: "https://twitter.com/alexis_conia"
  - name: github
    url: "https://github.com/alexisconia"
  - name: buymeacoffee
    url: "https://www.buymeacoffee.com/alexisconia"

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 10