baseURL: 'https://alexisconia.com'
languageCode: 'en-us'
title: 'Alexis CONIA'
theme: 'PaperMod'
defaultContentLanguage: en

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 2


params:
  env: production
  title: 'Alexis CONIA'
  description: 'Blog about Microsoft 365, Teams and videoconferencing'
  author: Me
  theme: 'PaperMod'

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: "Hi there \U0001F44B" # optional default will be site title
    subtitle: "This is subtitle"
    imageUrl: "/profile.png" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
  socialIcons:
  - name: twitter
    url: "https://twitter.com/alexis_conia"
  - name: stackoverflow
    url: "https://stackoverflow.com"
  - name: github
    url: "https://github.com/alexisconia"

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20